/* The following code was generated by JFlex 1.4.3 on 2/06/23 19:55 */

package codigo;
import static codigo.Tokens.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 2/06/23 19:55 from the specification file
 * <tt>D:/Escritorio/cccc/proyecto2/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\5\2\0\1\3\22\0\1\3\1\40\1\6\2\0"+
    "\1\43\1\36\1\0\1\44\1\45\1\35\1\33\1\3\1\34\1\0"+
    "\1\4\12\2\1\0\1\53\1\42\1\32\1\41\2\0\1\1\1\64"+
    "\1\1\1\56\1\65\3\1\1\57\2\1\1\61\1\1\1\63\1\66"+
    "\3\1\1\27\7\1\1\50\1\0\1\51\1\0\1\1\1\0\1\17"+
    "\1\7\1\15\1\25\1\12\1\24\1\23\1\16\1\13\2\1\1\21"+
    "\1\52\1\14\1\22\1\62\1\60\1\20\1\30\1\11\1\26\1\54"+
    "\1\31\1\1\1\10\1\55\1\46\1\37\1\47\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\15\2\1\10\1\11\1\12\1\13\3\14\2\15\1\1"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\2\1\24"+
    "\1\2\1\25\1\26\5\2\1\27\7\2\1\30\3\2"+
    "\1\15\1\31\1\14\1\0\7\2\1\32\6\2\1\33"+
    "\4\2\1\0\3\2\1\34\1\2\1\35\6\2\1\3"+
    "\1\2\1\36\6\2\1\37\6\2\1\40\7\2\1\41"+
    "\15\2\1\42\12\2\1\43\3\2\1\44\3\2\1\45"+
    "\1\46\4\2\1\47\1\50\1\2\1\51\1\2\1\52"+
    "\1\2\1\53";

  private static int [] zzUnpackAction() {
    int [] result = new int[166];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\67\0\67"+
    "\0\u014a\0\u0181\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb"+
    "\0\u0302\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483"+
    "\0\u04ba\0\u04f1\0\u0528\0\u0415\0\u055f\0\u0596\0\u04ba\0\u05cd"+
    "\0\67\0\67\0\67\0\67\0\67\0\u0604\0\67\0\u063b"+
    "\0\u0672\0\67\0\u06a9\0\u06e0\0\u0717\0\u074e\0\u0785\0\156"+
    "\0\u07bc\0\u07f3\0\u082a\0\u0861\0\u0898\0\u08cf\0\u0906\0\u093d"+
    "\0\u0974\0\u09ab\0\u09e2\0\67\0\67\0\67\0\u0a19\0\u0a50"+
    "\0\u0a87\0\u0abe\0\u0af5\0\u0b2c\0\u0b63\0\u0b9a\0\156\0\u0bd1"+
    "\0\u0c08\0\u0c3f\0\u0c76\0\u0cad\0\u0ce4\0\156\0\u0d1b\0\u0d52"+
    "\0\u0d89\0\u0dc0\0\u0df7\0\u0e2e\0\u0e65\0\u0e9c\0\156\0\u0ed3"+
    "\0\156\0\u0f0a\0\u0f41\0\u0f78\0\u0faf\0\u0fe6\0\u101d\0\67"+
    "\0\u1054\0\156\0\u108b\0\u10c2\0\u10f9\0\u1130\0\u1167\0\u119e"+
    "\0\156\0\u11d5\0\u120c\0\u1243\0\u127a\0\u12b1\0\u12e8\0\156"+
    "\0\u131f\0\u1356\0\u138d\0\u13c4\0\u13fb\0\u1432\0\u1469\0\156"+
    "\0\u14a0\0\u14d7\0\u150e\0\u1545\0\u157c\0\u15b3\0\u15ea\0\u1621"+
    "\0\u1658\0\u168f\0\u16c6\0\u16fd\0\u1734\0\156\0\u176b\0\u17a2"+
    "\0\u17d9\0\u1810\0\u1847\0\u187e\0\u18b5\0\u18ec\0\u1923\0\u195a"+
    "\0\156\0\u1991\0\u19c8\0\u19ff\0\156\0\u1a36\0\u1a6d\0\u1aa4"+
    "\0\156\0\156\0\u1adb\0\u1b12\0\u1b49\0\u1b80\0\156\0\156"+
    "\0\u1bb7\0\156\0\u1bee\0\156\0\u1c25\0\156";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[166];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\3\1\12\1\13\1\14\1\3\1\15\1\3\1\16"+
    "\1\3\1\17\1\3\1\20\1\21\1\22\1\3\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\6\3\1\50\4\3\70\0"+
    "\2\3\4\0\23\3\20\0\1\3\1\0\13\3\2\0"+
    "\1\4\67\0\1\5\67\0\1\51\25\0\1\52\35\0"+
    "\2\3\4\0\1\3\1\53\21\3\20\0\1\3\1\0"+
    "\13\3\1\0\2\3\4\0\11\3\1\54\1\3\1\55"+
    "\7\3\20\0\1\3\1\0\13\3\1\0\2\3\4\0"+
    "\12\3\1\56\10\3\20\0\1\3\1\0\13\3\1\0"+
    "\2\3\4\0\5\3\1\57\7\3\1\60\5\3\20\0"+
    "\1\3\1\0\13\3\1\0\2\3\4\0\7\3\1\61"+
    "\13\3\20\0\1\3\1\0\13\3\1\0\2\3\4\0"+
    "\23\3\20\0\1\3\1\0\1\62\12\3\1\0\2\3"+
    "\4\0\13\3\1\63\7\3\20\0\1\3\1\0\13\3"+
    "\1\0\2\3\4\0\4\3\1\64\16\3\20\0\1\3"+
    "\1\0\13\3\1\0\2\3\4\0\10\3\1\65\1\3"+
    "\1\66\1\67\7\3\20\0\1\3\1\0\13\3\1\0"+
    "\2\3\4\0\13\3\1\70\7\3\20\0\1\3\1\0"+
    "\13\3\1\0\2\3\4\0\2\3\1\71\20\3\20\0"+
    "\1\3\1\0\13\3\1\0\2\3\4\0\13\3\1\72"+
    "\7\3\20\0\1\3\1\0\13\3\1\0\2\3\4\0"+
    "\7\3\1\73\13\3\20\0\1\3\1\0\13\3\32\0"+
    "\1\74\66\0\1\52\1\75\65\0\1\52\1\0\1\75"+
    "\64\0\1\52\72\0\1\76\67\0\1\76\61\0\1\74"+
    "\6\0\1\74\57\0\1\74\7\0\1\74\60\0\1\77"+
    "\33\0\2\3\4\0\4\3\1\100\3\3\1\101\12\3"+
    "\20\0\1\3\1\0\13\3\1\0\2\3\4\0\4\3"+
    "\1\102\16\3\20\0\1\3\1\0\13\3\5\51\1\0"+
    "\61\51\1\0\2\3\4\0\2\3\1\103\20\3\20\0"+
    "\1\3\1\0\13\3\1\0\2\3\4\0\17\3\1\104"+
    "\3\3\20\0\1\3\1\0\13\3\1\0\2\3\4\0"+
    "\23\3\20\0\1\105\1\0\13\3\1\0\2\3\4\0"+
    "\21\3\1\106\1\3\20\0\1\3\1\0\13\3\1\0"+
    "\2\3\4\0\2\3\1\107\20\3\20\0\1\3\1\0"+
    "\13\3\1\0\2\3\4\0\10\3\1\110\12\3\20\0"+
    "\1\3\1\0\13\3\1\0\2\3\4\0\10\3\1\111"+
    "\12\3\20\0\1\3\1\0\13\3\1\0\2\3\4\0"+
    "\5\3\1\112\15\3\20\0\1\3\1\0\13\3\1\0"+
    "\2\3\4\0\11\3\1\113\11\3\20\0\1\3\1\0"+
    "\13\3\1\0\2\3\4\0\12\3\1\114\10\3\20\0"+
    "\1\3\1\0\13\3\1\0\2\3\4\0\13\3\1\115"+
    "\7\3\20\0\1\3\1\0\13\3\1\0\2\3\4\0"+
    "\11\3\1\116\11\3\20\0\1\3\1\0\13\3\1\0"+
    "\2\3\4\0\17\3\1\117\3\3\20\0\1\3\1\0"+
    "\13\3\1\0\2\3\4\0\11\3\1\120\11\3\20\0"+
    "\1\3\1\0\13\3\1\0\2\3\4\0\12\3\1\121"+
    "\10\3\20\0\1\3\1\0\13\3\1\0\2\3\4\0"+
    "\4\3\1\122\16\3\20\0\1\3\1\0\13\3\2\0"+
    "\1\123\65\0\2\3\4\0\11\3\1\124\11\3\20\0"+
    "\1\3\1\0\13\3\1\0\2\3\4\0\4\3\1\125"+
    "\16\3\20\0\1\3\1\0\13\3\1\0\2\3\4\0"+
    "\5\3\1\126\15\3\20\0\1\3\1\0\13\3\1\0"+
    "\2\3\4\0\3\3\1\107\17\3\20\0\1\3\1\0"+
    "\13\3\1\0\2\3\4\0\3\3\1\127\17\3\20\0"+
    "\1\3\1\0\13\3\1\0\2\3\4\0\10\3\1\130"+
    "\12\3\20\0\1\3\1\0\13\3\1\0\2\3\4\0"+
    "\3\3\1\131\17\3\20\0\1\3\1\0\13\3\1\0"+
    "\2\3\4\0\11\3\1\107\11\3\20\0\1\3\1\0"+
    "\13\3\1\0\2\3\4\0\5\3\1\132\15\3\20\0"+
    "\1\3\1\0\13\3\1\0\2\3\4\0\14\3\1\107"+
    "\6\3\20\0\1\3\1\0\13\3\1\0\2\3\4\0"+
    "\10\3\1\133\12\3\20\0\1\3\1\0\13\3\1\0"+
    "\2\3\4\0\21\3\1\104\1\3\20\0\1\3\1\0"+
    "\13\3\1\0\2\3\4\0\10\3\1\57\12\3\20\0"+
    "\1\3\1\0\13\3\1\0\2\3\4\0\1\134\22\3"+
    "\20\0\1\3\1\0\13\3\1\0\2\3\4\0\4\3"+
    "\1\135\16\3\20\0\1\3\1\0\13\3\1\0\2\3"+
    "\4\0\2\3\1\136\20\3\20\0\1\3\1\0\13\3"+
    "\1\0\2\3\4\0\12\3\1\137\10\3\20\0\1\3"+
    "\1\0\13\3\2\0\1\123\42\0\1\140\22\0\2\3"+
    "\4\0\10\3\1\141\12\3\20\0\1\3\1\0\13\3"+
    "\1\0\2\3\4\0\5\3\1\142\15\3\20\0\1\3"+
    "\1\0\13\3\1\0\2\3\4\0\2\3\1\143\20\3"+
    "\20\0\1\3\1\0\13\3\1\0\2\3\4\0\11\3"+
    "\1\144\11\3\20\0\1\3\1\0\13\3\1\0\2\3"+
    "\4\0\23\3\20\0\1\3\1\0\1\3\1\145\11\3"+
    "\1\0\2\3\4\0\11\3\1\146\11\3\20\0\1\3"+
    "\1\0\13\3\1\0\2\3\4\0\12\3\1\103\10\3"+
    "\20\0\1\3\1\0\13\3\1\0\2\3\4\0\5\3"+
    "\1\147\15\3\20\0\1\3\1\0\13\3\1\0\2\3"+
    "\4\0\10\3\1\150\12\3\20\0\1\3\1\0\13\3"+
    "\1\0\2\3\4\0\3\3\1\151\17\3\20\0\1\3"+
    "\1\0\13\3\1\0\2\3\4\0\11\3\1\152\11\3"+
    "\20\0\1\3\1\0\13\3\1\0\2\3\4\0\10\3"+
    "\1\153\12\3\20\0\1\3\1\0\13\3\1\0\2\3"+
    "\4\0\23\3\20\0\1\3\1\0\5\3\1\154\5\3"+
    "\1\0\2\3\4\0\10\3\1\155\12\3\20\0\1\3"+
    "\1\0\13\3\1\0\2\3\4\0\23\3\20\0\1\3"+
    "\1\0\2\3\1\156\1\157\7\3\1\0\2\3\4\0"+
    "\14\3\1\160\6\3\20\0\1\3\1\0\13\3\1\0"+
    "\2\3\4\0\11\3\1\161\11\3\20\0\1\3\1\0"+
    "\13\3\1\0\2\3\4\0\20\3\1\162\2\3\20\0"+
    "\1\3\1\0\7\3\1\163\1\3\1\164\1\165\1\0"+
    "\2\3\4\0\11\3\1\166\11\3\20\0\1\3\1\0"+
    "\13\3\1\0\2\3\4\0\10\3\1\167\12\3\20\0"+
    "\1\3\1\0\13\3\1\0\2\3\4\0\11\3\1\170"+
    "\11\3\20\0\1\3\1\0\13\3\1\0\2\3\4\0"+
    "\3\3\1\171\17\3\20\0\1\3\1\0\13\3\1\0"+
    "\2\3\4\0\23\3\20\0\1\3\1\0\1\3\1\172"+
    "\11\3\1\0\2\3\4\0\23\3\20\0\1\3\1\0"+
    "\5\3\1\173\5\3\1\0\2\3\4\0\17\3\1\174"+
    "\3\3\20\0\1\3\1\0\13\3\1\0\2\3\4\0"+
    "\13\3\1\175\7\3\20\0\1\3\1\0\13\3\1\0"+
    "\2\3\4\0\21\3\1\176\1\3\20\0\1\3\1\0"+
    "\13\3\1\0\2\3\4\0\3\3\1\177\17\3\20\0"+
    "\1\3\1\0\13\3\1\0\2\3\4\0\23\3\20\0"+
    "\1\3\1\0\7\3\1\200\1\201\2\3\1\0\2\3"+
    "\4\0\23\3\20\0\1\3\1\0\6\3\1\202\4\3"+
    "\1\0\2\3\4\0\11\3\1\203\11\3\20\0\1\3"+
    "\1\0\13\3\1\0\2\3\4\0\23\3\20\0\1\3"+
    "\1\0\4\3\1\204\6\3\1\0\2\3\4\0\10\3"+
    "\1\205\12\3\20\0\1\3\1\0\13\3\1\0\2\3"+
    "\4\0\11\3\1\206\11\3\20\0\1\3\1\0\13\3"+
    "\1\0\2\3\4\0\11\3\1\207\11\3\20\0\1\3"+
    "\1\0\13\3\1\0\2\3\4\0\2\3\1\210\20\3"+
    "\20\0\1\3\1\0\13\3\1\0\2\3\4\0\21\3"+
    "\1\211\1\3\20\0\1\3\1\0\13\3\1\0\2\3"+
    "\4\0\3\3\1\212\17\3\20\0\1\3\1\0\13\3"+
    "\1\0\2\3\4\0\12\3\1\213\10\3\20\0\1\3"+
    "\1\0\13\3\1\0\2\3\4\0\4\3\1\214\16\3"+
    "\20\0\1\3\1\0\13\3\1\0\2\3\4\0\3\3"+
    "\1\215\17\3\20\0\1\3\1\0\13\3\1\0\2\3"+
    "\4\0\17\3\1\216\3\3\20\0\1\3\1\0\13\3"+
    "\1\0\2\3\4\0\23\3\20\0\1\3\1\0\6\3"+
    "\1\217\4\3\1\0\2\3\4\0\2\3\1\220\20\3"+
    "\20\0\1\3\1\0\13\3\1\0\2\3\4\0\3\3"+
    "\1\221\17\3\20\0\1\3\1\0\13\3\1\0\2\3"+
    "\4\0\2\3\1\222\20\3\20\0\1\3\1\0\13\3"+
    "\1\0\2\3\4\0\14\3\1\223\6\3\20\0\1\3"+
    "\1\0\13\3\1\0\2\3\4\0\10\3\1\224\12\3"+
    "\20\0\1\3\1\0\13\3\1\0\2\3\4\0\23\3"+
    "\20\0\1\3\1\0\1\3\1\225\11\3\1\0\2\3"+
    "\4\0\6\3\1\226\14\3\20\0\1\3\1\0\13\3"+
    "\1\0\2\3\4\0\4\3\1\227\16\3\20\0\1\3"+
    "\1\0\13\3\1\0\2\3\4\0\4\3\1\230\16\3"+
    "\20\0\1\3\1\0\13\3\1\0\2\3\4\0\3\3"+
    "\1\231\17\3\20\0\1\3\1\0\13\3\1\0\2\3"+
    "\4\0\3\3\1\232\17\3\20\0\1\3\1\0\13\3"+
    "\1\0\2\3\4\0\11\3\1\233\11\3\20\0\1\3"+
    "\1\0\13\3\1\0\2\3\4\0\5\3\1\234\15\3"+
    "\20\0\1\3\1\0\13\3\1\0\2\3\4\0\7\3"+
    "\1\235\13\3\20\0\1\3\1\0\13\3\1\0\2\3"+
    "\4\0\3\3\1\236\17\3\20\0\1\3\1\0\13\3"+
    "\1\0\2\3\4\0\23\3\20\0\1\3\1\0\1\3"+
    "\1\237\11\3\1\0\2\3\4\0\13\3\1\240\7\3"+
    "\20\0\1\3\1\0\13\3\1\0\2\3\4\0\6\3"+
    "\1\241\14\3\20\0\1\3\1\0\13\3\1\0\2\3"+
    "\4\0\10\3\1\242\12\3\20\0\1\3\1\0\13\3"+
    "\1\0\2\3\4\0\11\3\1\243\11\3\20\0\1\3"+
    "\1\0\13\3\1\0\2\3\4\0\13\3\1\244\7\3"+
    "\20\0\1\3\1\0\13\3\1\0\2\3\4\0\16\3"+
    "\1\245\4\3\20\0\1\3\1\0\13\3\1\0\2\3"+
    "\4\0\10\3\1\246\12\3\20\0\1\3\1\0\13\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7260];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\2\11\30\1\5\11\1\1\1\11"+
    "\2\1\1\11\21\1\3\11\1\0\23\1\1\0\14\1"+
    "\1\11\106\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[166];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 156) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 8: 
          { lexeme = yytext(); return Igual;
          }
        case 44: break;
        case 31: 
          { lexeme = yytext(); return While;
          }
        case 45: break;
        case 14: 
          { lexeme = yytext(); return Parentesis_a;
          }
        case 46: break;
        case 41: 
          { lexeme = yytext(); return GirarDerecha;
          }
        case 47: break;
        case 36: 
          { lexeme = yytext(); return TomarLapiz;
          }
        case 48: break;
        case 3: 
          { lexeme = yytext(); return Numero;
          }
        case 49: break;
        case 6: 
          { return Linea;
          }
        case 50: break;
        case 23: 
          { lexeme = yytext(); return If;
          }
        case 51: break;
        case 38: 
          { lexeme = yytext(); return MirarOeste;
          }
        case 52: break;
        case 2: 
          { lexeme = yytext(); return Identificador;
          }
        case 53: break;
        case 9: 
          { lexeme = yytext(); return Suma;
          }
        case 54: break;
        case 13: 
          { lexeme = yytext(); return Op_relacional;
          }
        case 55: break;
        case 12: 
          { lexeme = yytext(); return Op_logico;
          }
        case 56: break;
        case 22: 
          { lexeme = yytext(); return Op_atribucion;
          }
        case 57: break;
        case 25: 
          { lexeme = yytext(); return Op_incremento;
          }
        case 58: break;
        case 32: 
          { lexeme = yytext(); return Cadena;
          }
        case 59: break;
        case 15: 
          { lexeme = yytext(); return Parentesis_c;
          }
        case 60: break;
        case 29: 
          { lexeme = yytext(); return Else;
          }
        case 61: break;
        case 42: 
          { lexeme = yytext(); return PintarBlanco;
          }
        case 62: break;
        case 26: 
          { lexeme = yytext(); return T_dato;
          }
        case 63: break;
        case 18: 
          { lexeme = yytext(); return Corchete_a;
          }
        case 64: break;
        case 4: 
          { /* Ignorar espacios en blanco */
          }
        case 65: break;
        case 21: 
          { /* Ignorar comentarios */
          }
        case 66: break;
        case 16: 
          { lexeme = yytext(); return Llave_a;
          }
        case 67: break;
        case 37: 
          { lexeme = yytext(); return MirarNorte;
          }
        case 68: break;
        case 40: 
          { lexeme = yytext(); return PintarNegro;
          }
        case 69: break;
        case 39: 
          { lexeme = yytext(); return SoltarLapiz;
          }
        case 70: break;
        case 34: 
          { lexeme = yytext(); return MirarSur;
          }
        case 71: break;
        case 35: 
          { lexeme = yytext(); return MirarEste;
          }
        case 72: break;
        case 5: 
          { lexeme = yytext(); return Division;
          }
        case 73: break;
        case 43: 
          { lexeme = yytext(); return GirarIzquierda;
          }
        case 74: break;
        case 27: 
          { lexeme = yytext(); return For;
          }
        case 75: break;
        case 33: 
          { lexeme = yytext(); return Avanzar;
          }
        case 76: break;
        case 10: 
          { lexeme = yytext(); return Resta;
          }
        case 77: break;
        case 19: 
          { lexeme = yytext(); return Corchete_c;
          }
        case 78: break;
        case 1: 
          { return ERROR;
          }
        case 79: break;
        case 7: 
          { lexeme = yytext(); return Comillas;
          }
        case 80: break;
        case 20: 
          { lexeme = yytext(); return P_coma;
          }
        case 81: break;
        case 24: 
          { lexeme = yytext(); return Do;
          }
        case 82: break;
        case 11: 
          { lexeme = yytext(); return Multiplicacion;
          }
        case 83: break;
        case 17: 
          { lexeme = yytext(); return Llave_c;
          }
        case 84: break;
        case 28: 
          { lexeme = yytext(); return Op_booleano;
          }
        case 85: break;
        case 30: 
          { lexeme = yytext(); return Main;
          }
        case 86: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
